name: Release Validation in Prod

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  call-workflow-passing-data:
    uses: pranayjswl007/ultimate-devops/.github/workflows/main-validate.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      personal_access_token: ${{ secrets.token }}
