name: PR validation in develop

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop

jobs:
  call-templated-workflow:
    uses: pranayjswl007/ultimate-devops/.github/workflows/develop-validate-uat.yml@main
    secrets: inherit # pass all secrets
    with:
      environment-name: uat
