name: PR validation in develop

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop

jobs:
  develop-pr-validation:
    uses: pranayjswl007/ultimate-devops/.github/workflows/validate.yml@main
    secrets: inherit # pass all secrets
    with:
      environment-name: uat
      runQualityCheck: true
      runJestTests: true
      deployFromBranch: develop
