name: PR deployment in develop

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  develop-pr-deployment:
    if: github.event.pull_request.merged == true
    uses: pranayjswl007/ultimate-devops/.github/workflows/deploy.yml@main
    secrets: inherit # pass all secrets
    with:
      environment-name: uat
