name: PR validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop # Only trigger when PR targets develop

jobs:
  # 🧪 Run validation if source branch starts with promotion-ga
  develop-pr-validation:
    if: startsWith(github.head_ref, 'promotions/')
    uses: pranayjswl007/ultimate-devops/.github/workflows/validate.yml@main
    secrets: inherit
    with:
      environment-name: uat
      runQualityCheck: true
      runJestTests: true
      deployFromBranch: develop

  # 🚀 Auto-promote if source branch does NOT start with promotion-ga
  auto-promote:
    if: startsWith(github.head_ref, 'promotions/') == false
    uses: pranayjswl007/ultimate-devops/.github/workflows/auto-promote.yml@main
    secrets: inherit
    with:
      head-ref: ${{ github.head_ref }}
      base-ref: ${{ github.base_ref }}
      pr-number: ${{ github.event.pull_request.number }}
      repository: ${{ github.repository }}
