name: Release Deployment in production/main

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  main-pr-deployment:
    if: github.event.pull_request.merged == true
    uses: pranayjswl007/ultimate-devops/.github/workflows/deploy.yml@main
    secrets: inherit # pass all secrets
    with:
      environment-name: production
