name: Release Validation in Prod

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  call-templated-workflow:
    uses: pranayjswl007/ultimate-devops/.github/workflows/main-validate.yml@main
    secrets: inherit # pass all secrets
    with:
      environment-name: production
