name: Nightly Code Scan

# on:
#   schedule:
#     - cron: "0 2 * * *" # Runs at 2:00 AM every day
on:
  push:
    branches:
      - develop
      - main

jobs:
  call-workflow-passing-data:
    uses: pranayjswl007/ultimate-devops/.github/workflows/code-scanner.yml@main
    secrets: inherit # pass all secrets

